### ISSUE TITLE
Filtering step fails

### ISSUE THREAD

**Issue by 5utr** [Nesvilab/philosopher#29]
I tried running philosopher (20181128) on a sample but it fails at the filtering step.

`
./philosopher_linux_amd64 workspace --clean
./philosopher_linux_amd64 workspace --init
./philosopher_linux_amd64 comet --param comet.params TMT1_1.mzML
./philosopher_linux_amd64 peptideprophet --database 2019-01-08-td-UP000005640.fas --accmass --decoy rev_ --decoyprobs --nonparam TMT1_1.pep.xml
./philosopher_linux_amd64 proteinprophet interact-TMT1_1.pep.xml
./philosopher_linux_amd64 filter --pepxml interact-TMT1_1.pep.xml
./philosopher_linux_amd64 filter --pepxml interact-TMT1_1.pep.xml
INFO[10:18:51] Executing Filter 20181128
INFO[10:18:51] Processing peptide identification files
INFO[10:18:54] 1+ Charge profile                             decoy=0 target=0
INFO[10:18:54] 2+ Charge profile                             decoy=540 target=7375
INFO[10:18:54] 3+ Charge profile                             decoy=710 target=8356
INFO[10:18:54] 4+ Charge profile                             decoy=177 target=2261
INFO[10:18:54] 5+ Charge profile                             decoy=0 target=0
INFO[10:18:54] 6+ Charge profile                             decoy=0 target=0
INFO[10:18:54] Database search results                       ions=8208 peptides=6996 psms=19419
INFO[10:18:54] Converged to 1.00 % FDR with 16116 PSMs       decoy=162 threshold=0.7821 total=16278
INFO[10:18:54] Converged to 0.99 % FDR with 4944 Peptides    decoy=49 threshold=0.9156 total=4993
INFO[10:18:54] Converged to 0.99 % FDR with 6038 Ions        decoy=60 threshold=0.8988 total=6098
FATA[10:18:54] Database data not available, interrupting processing`

**Comment by 5utr** [comment]
I did run the database command before but I just tried again and I get the same error.

`-bash-4.2$ ./philosopher_linux_amd64 workspace --clean
INFO[13:04:22] Executing Workspace 20181128
WARN[13:04:23] GitHub unreachable for the moment, can't check for versions right now.
INFO[13:04:23] Removing workspace
INFO[13:04:23] Done
-bash-4.2$ ./philosopher_linux_amd64 workspace --init
INFO[13:04:23] Executing Workspace 20181128
WARN[13:04:23] GitHub unreachable for the moment, can't check for versions right now.
INFO[13:04:23] Creating workspace
INFO[13:04:23] Done
-bash-4.2$ ./philosopher_linux_amd64 database --id UP000005640 --contam --reviewed
INFO[13:04:23] Executing Database 20181128
INFO[13:04:23] Fetching database
INFO[13:04:34] Processing decoys
INFO[13:04:35] Creating file
INFO[13:04:36] Done
-bash-4.2$ ./philosopher_linux_amd64 comet --param comet.params TMT1_1.mzML
INFO[13:04:36] Executing Comet 20181128
INFO[13:04:36] Indexing spectra: please wait, this can take a few minutes
INFO[13:04:36] Indexing TMT1_1.mzML
 Comet version "2017.01 rev. 2"

 Search start:  01/09/2019, 01:05:59 PM
 - Input file: /projects/ptx_analysis/gnegri/philosopher/TMT1_1.mzML
   - Load spectra: 39069
     - Search progress:  99%
     - Post analysis:  done
 Search end:    01/09/2019, 01:06:41 PM, 0m:42s

INFO[13:06:44] Done
-bash-4.2$ ./philosopher_linux_amd64 peptideprophet --database 2019-01-09-td-UP000005640.fas --accmass --decoy rev_ --decoyprobs --nonparam TMT1_1.pep.xml
INFO[13:06:45] Executing PeptideProphet 20181128
 file 1: /projects/ptx_analysis/gnegri/philosopher/TMT1_1.pep.xml
 processed altogether 39069 results
INFO: Results written to file: /projects/ptx_analysis/gnegri/philosopher/interact-TMT1_1.pep.xml

  - /projects/ptx_analysis/gnegri/philosopher/interact-TMT1_1.pep.xml
  - Building Commentz-Walter keyword tree...
  - Searching the tree...
  - Linking duplicate entries...
  - Printing results...

using Accurate Mass Bins
Using Decoy Label "rev_".
Decoy Probabilities will be reported.
Using non-parametric distributions
 (Comet)
adding ACCMASS mixture distribution
init with Comet trypsin
MS Instrument info: Manufacturer: UNKNOWN, Model: UNKNOWN, Ionization: UNKNOWN, Analyzer: UNKNOWN, Detector: UNKNOWN

INFO: Processing standard MixtureModel ...
 PeptideProphet  (TPP v5.0.1 Post-Typhoon dev, Build 201705191541-exported (Linux-x86_64)) AKeller@ISB
 read in 0 1+, 12529 2+, 16050 3+, 5645 4+, 0 5+, 0 6+, and 0 7+ spectra.
Initialising statistical models ...
Found 10611 Decoys, and 23613 Non-Decoys
Iterations: .........10.........20.....
WARNING: Mixture model quality test failed for charge (1+).
WARNING: Mixture model quality test failed for charge (5+).
WARNING: Mixture model quality test failed for charge (6+).
WARNING: Mixture model quality test failed for charge (7+).
model complete after 26 iterations
INFO[13:07:29] Done
-bash-4.2$ ./philosopher_linux_amd64 proteinprophet interact-TMT1_1.pep.xml
INFO[13:07:29] Executing ProteinProphet 20181128
ProteinProphet (C++) by Insilicos LLC and LabKey Software, after the original Perl by A. Keller (TPP v5.0.1 Post-Typhoon dev, Build 201705221614-exported (Linux-x86_64))
 (no FPKM) (using degen pep info)
Reading in /projects/ptx_analysis/gnegri/philosopher/interact-TMT1_1.pep.xml...
...read in 0 1+, 7665 2+, 8742 3+, 2344 4+, 0 5+, 0 6+, 0 7+ spectra with min prob 0.05

Initializing 7722 peptide weights: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
Calculating protein lengths and molecular weights from database /projects/ptx_analysis/gnegri/philosopher/2019-01-09-td-UP000005640.fas
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........1000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........2000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........3000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........4000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........5000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........6000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........7000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........8000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........9000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........10000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........11000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........12000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........13000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........14000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........15000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........16000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........17000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........18000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........19000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........20000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........21000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........22000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........23000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........24000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........25000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........26000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........27000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........28000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........29000
.........:......WARNING: Found the following zero-mass residues in protein entry sp|Q16881|TRXR1_HUMAN : U
MGCAEGKAVAAAAPTELQTKGKNGDGRRRSAKDHHPGKTLPENPAGFTSTATADSRALLQAYIDGHSVVIFSRSTCTRCTEVKKLFKSLCVPYFVLELDQTEDGRALEGTLSELAAETDLPVVFVKQRKIGGHGPTLKAYQEGRLQKLLKMNGPEDLPKSYDYDLIIIGGGSGGLAAAKEAAQYGKKVMVLDFVTPTPLGTRWGLGGTCVNVGCIPKKLMHQAALLGQALQDSRNYGWKVEETVKHDWDRMIEAVQNHIGSLNWGYRVALREKKVVYENAYGQFIGPHRIKATNNKGKEKIYSAERFLIATGERPRYLGIPGDKEYCISSDDLFSLPYCPGKTLVVGASYVALECAGFLAGIGLDVTVMVRSILLRGFDQDMANKIGEHMEEHGIKFIRQFVPIKVEQIEAGTPGRLRVVAQSTNSEEIIEGEYNTVMLAIGRDACTRKIGLETVGVKINEKTGKIPVTDEEQTNVPYIYAIGDILEDKVELTPVAIQAGRLLAQRLYAGSTVKCDYENVPTTVFTPLEYGACGLSEEKAVEKFGEENIEVYHSYFWPLEWTIPSRDNNKCYAKIICNTKDNERVVGFHVLGPNAGEVTQGFAAALKCGLTKKQLDSTIGIHPVCAEVFTTLSVTKRSGASILQAGCUG
...:.........:.........:.........:.........:.........:.........:.........:.........30000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........31000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........32000
.........:.........:......WARNING: Found the following zero-mass residues in protein entry sp|Q86VQ6|TRXR3_HUMAN : U
MERSPPQSPGPGKAGDAPNRRSGHVRGARVLSPPGRRARLSSPGPSRSSEAREELRRHLVGLIERSRVVIFSKSYCPHSTRVKELFSSLGVECNVLELDQVDDGARVQEVLSEITNQKTVPNIFVNKVHVGGCDQTFQAYQSGLLQKLLQEDLAYDYDLIIIGGGSGGLSCAKEAAILGKKVMVLDFVVPSPQGTSWGLGGTCVNVGCIPKKLMHQAALLGQALCDSRKFGWEYNQQVRHNWETMTKAIQNHISSLNWGYRLSLREKAVAYVNSYGEFVEHHKIKATNKKGQETYYTAAQFVIATGERPRYLGIQGDKEYCITSDDLFSLPYCPGKTLVVGASYVALECAGFLAGFGLDVTVMVRSILLRGFDQEMAEKVGSYMEQHGVKFLRKFIPVMVQQLEKGSPGKLKVLAKSTEGTETIEGVYNTVLLAIGRDSCTRKIGLEKIGVKINEKSGKIPVNDVEQTNVPYVYAVGDILEDKPELTPVAIQSGKLLAQRLFGASLEKCDYINVPTTVFTPLEYGCCGLSEEKAIEVYKKENLEIYHTLFWPLEWTVAGRENNTCYAKIICNKFDHDRVIGFHILGPNAGEVTQGFAAAMKCGLTKQLLDDTIGIHPTCGEVFTTLEITKSSGLDITQKGCUG
...:.........:.........:.........:.........:.........:.........:.........33000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........34000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........35000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........36000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........37000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........38000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........39000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........40000
.........:.........:.........:.........:.........:.........:.........:.........:.........  Total: 40894
Computing degenerate peptides for 3907 proteins: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
Computing probabilities for 4066 proteins.  Loop 1: 0%...20%...40%...60%...80%...100%  Loop 2: 0%...20%...40%...60%...80%...100%
Computing probabilities for 4066 proteins.  Loop 1: 0%...20%...40%...60%...80%...100%  Loop 2: 0%...20%...40%...60%...80%...100%
Computing probabilities for 4066 proteins.  Loop 1: 0%...20%...40%...60%...80%...100%  Loop 2: 0%...20%...40%...60%...80%...100%
Computing probabilities for 4066 proteins.  Loop 1: 0%...20%...40%...60%...80%...100%  Loop 2: 0%...20%...40%...60%...80%...100%
Computing probabilities for 4066 proteins.  Loop 1: 0%...20%...40%...60%...80%...100%  Loop 2: 0%...20%...40%...60%...80%...100%
Computing 3646 protein groups: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
Calculating sensitivity...and error tables...
Computing MU for 4066 proteins: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
INFO: mu=2.2265e-05, db_size=45483563

Finished
INFO[13:07:35] Done
-bash-4.2$ ./philosopher_linux_amd64 filter --pepxml interact-TMT1_1.pep.xml
INFO[13:07:35] Executing Filter 20181128
INFO[13:07:35] Processing peptide identification files
INFO[13:07:38] 1+ Charge profile                             decoy=0 target=0
INFO[13:07:38] 2+ Charge profile                             decoy=540 target=7375
INFO[13:07:38] 3+ Charge profile                             decoy=711 target=8356
INFO[13:07:38] 4+ Charge profile                             decoy=177 target=2261
INFO[13:07:38] 5+ Charge profile                             decoy=0 target=0
INFO[13:07:38] 6+ Charge profile                             decoy=0 target=0
INFO[13:07:38] Database search results                       ions=8208 peptides=6996 psms=19420
INFO[13:07:38] Converged to 1.00 % FDR with 16116 PSMs       decoy=162 threshold=0.7821 total=16278
INFO[13:07:38] Converged to 0.99 % FDR with 4944 Peptides    decoy=49 threshold=0.9156 total=4993
INFO[13:07:39] Converged to 0.99 % FDR with 6038 Ions        decoy=60 threshold=0.8988 total=6098
FATA[13:07:39] Database data not available, interrupting processing
`

**Comment by prvst** [comment]
are you running it through FragPipe ?

**Comment by 5utr** [comment]
No, just following the example on github.

**Comment by prvst** [comment]
are you using the latest version ? If not I suggest trying the latest release

**Comment by 5utr** [comment]
Yes I'm using the 20181128 version.

**Comment by HYTang69** [comment]
Hi, I also have the same problem with philosopher 20190116, i.e. fatal error "Database data not available, interrupting processing" during filtering. I also ran the database command, and not using FragPipe.

D:\Users\tangh\Desktop\Philosopher\Test>philosopher filter --pepxml interact-alt
ierid-17-g129-lonp1-normoxia-trypsin4ul-hf.pep.xml
INFO[20:45:38] Executing Filter 20190116
INFO[20:45:38] Processing peptide identification files
INFO[20:45:39] 1+ Charge profile                             decoy=0 target=0
INFO[20:45:39] 2+ Charge profile                             decoy=798 target=67
93
INFO[20:45:39] 3+ Charge profile                             decoy=443 target=41
32
INFO[20:45:39] 4+ Charge profile                             decoy=43 target=644

INFO[20:45:39] 5+ Charge profile                             decoy=7 target=137
INFO[20:45:39] 6+ Charge profile                             decoy=10 target=78
INFO[20:45:39] Database search results                       ions=7850 peptides=
6703 psms=13085
INFO[20:45:39] Converged to 1.00 % FDR with 9549 PSMs        decoy=96 threshold=
0.8366 total=9645
INFO[20:45:39] Converged to 0.99 % FDR with 3911 Peptides    decoy=39 threshold=
0.917 total=3950
INFO[20:45:39] Converged to 1.00 % FDR with 4888 Ions        decoy=49 threshold=
0.9052 total=4937
FATA[20:45:40] Database data not available, interrupting processing

**Comment by prvst** [comment]
@HYTang69 , did you ran the database command before ? If so, can you paste your command here ?

**Comment by HYTang69** [comment]
Here is the database command:
D:\Users\tangh\Desktop\Philosopher\Test>philosopher database --id UP000005640 --
contam --reviewed
INFO[17:11:41] Executing Database 20190116
INFO[17:11:41] Fetching database
INFO[17:12:00] Processing decoys
INFO[17:12:01] Creating file
INFO[17:12:02] Done

**Comment by HYTang69** [comment]
Here is the entire command and response.

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\tangh>d:

D:\>cd D:\Users\tangh\Desktop\Philosopher\Test

D:\Users\tangh\Desktop\Philosopher\Test>philosopher workspace --init
INFO[17:10:04] Executing Workspace 20190116
INFO[17:10:04] Creating workspace
INFO[17:10:04] Done

D:\Users\tangh\Desktop\Philosopher\Test>philosopher database --id UP000005640 --
contam --reviewed
INFO[17:11:41] Executing Database 20190116
INFO[17:11:41] Fetching database
INFO[17:12:00] Processing decoys
INFO[17:12:01] Creating file
INFO[17:12:02] Done

D:\Users\tangh\Desktop\Philosopher\Test>philosopher comet --print
INFO[17:12:26] Executing Comet 20190116
INFO[17:12:26] Printing parameter file
INFO[17:12:27] Done

D:\Users\tangh\Desktop\Philosopher\Test>philosopher comet --param comet.params A
ltieriD-17-G129-LonP1-Normoxia-Trypsin4ul-HF.mzXML
INFO[17:17:32] Executing Comet 20190116
FATA[17:17:33] open D:\Users\tangh\Desktop\Philosopher\Test\comet.params: The sy
stem cannot find the file specified.

D:\Users\tangh\Desktop\Philosopher\Test>philosopher comet --param comet.params A
ltieriD-17-G129-LonP1-Normoxia-Trypsin4ul-HF.mzXML
INFO[17:17:48] Executing Comet 20190116
INFO[17:17:48] mz file format not supported for indexing, skipping the indexing

 Comet version "2017.01 rev. 2"

 Search start:  01/29/2019, 05:17:48 PM
 - Input file: D:\Users\tangh\Desktop\Philosopher\Test\AltieriD-17-G129-LonP1-No
rmoxia-Trypsin4ul-HF.mzXML
   - Load spectra: 36424
     - Search progress: 100%
     - Post analysis:  done
 Search end:    01/29/2019, 05:20:03 PM, 2m:15s

INFO[17:20:03] Done

D:\Users\tangh\Desktop\Philosopher\Test>philosopher peptideprophet --database 20
19-01-29-td-UP000005640.fas --accmass --decoy rev_ --decoyprobs --nonparam Altie
riD-17-G129-LonP1-Normoxia-Trypsin4ul-HF.pep.xml
INFO[20:33:13] Executing PeptideProphet 20190116
 file 1: D:\Users\tangh\Desktop\Philosopher\Test\AltieriD-17-G129-LonP1-Normoxia
-Trypsin4ul-HF.pep.xml
 processed altogether 36424 results
INFO: Results written to file: D:\Users\tangh\Desktop\Philosopher\Test\interact-
AltieriD-17-G129-LonP1-Normoxia-Trypsin4ul-HF.pep.xml

  - D:\Users\tangh\Desktop\Philosopher\Test\interact-AltieriD-17-G129-LonP1-Norm
oxia-Trypsin4ul-HF.pep.xml
  - Building Commentz-Walter keyword tree...
  - Searching the tree...
  - Linking duplicate entries...
  - Printing results...

using Accurate Mass Bins
Using Decoy Label "rev_".
Decoy Probabilities will be reported.
Using non-parametric distributions
 (Comet)
adding ACCMASS mixture distribution
init with Comet stricttrypsin
MS Instrument info: Manufacturer: Thermo Scientific, Model: Q Exactive, Ionizati
on: UNKNOWN, Analyzer: UNKNOWN, Detector: UNKNOWN

INFO: Processing standard MixtureModel ...
 PeptideProphet  (TPP v5.0.1 Post-Typhoon dev, Build 201705191533-7588 (Windows_
NT-x86_64)) AKeller@ISB
 read in 0 1+, 14352 2+, 12821 3+, 4745 4+, 1613 5+, 555 6+, and 0 7+ spectra.
Initialising statistical models ...
Found 11544 Decoys, and 22542 Non-Decoys
Iterations: .........10.........20.......
WARNING: Mixture model quality test failed for charge (1+).
WARNING: Mixture model quality test failed for charge (7+).
model complete after 28 iterations
INFO[20:34:14] Done

D:\Users\tangh\Desktop\Philosopher\Test>philosopher proteinprophet interact-alti
erid-17-g129-lonp1-normoxia-trypsin4ul-hf.pep.xml
INFO[20:42:03] Executing ProteinProphet 20190116
ProteinProphet (C++) by Insilicos LLC and LabKey Software, after the original Pe
rl by A. Keller (TPP v5.0.1 Post-Typhoon dev, Build 201705191533-7588 (Windows_N
T-x86_64))
 (no FPKM) (using degen pep info)
Reading in D:/Users/tangh/Desktop/Philosopher/Test/interact-altierid-17-g129-lon
p1-normoxia-trypsin4ul-hf.pep.xml...
...read in 0 1+, 7590 2+, 4575 3+, 686 4+, 144 5+, 88 6+, 0 7+ spectra with min
prob 0.05

Initializing 7871 peptide weights: 0%...10%...20%...30%...40%...50%...60%...70%.
..80%...90%...100%
Calculating protein lengths and molecular weights from database d:/Users/tangh/D
esktop/Philosopher/Test/2019-01-29-td-UP000005640.fas
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........1000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........2000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........3000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........4000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........5000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........6000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........7000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........8000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........9000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........10000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........11000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........12000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........13000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........14000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........15000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........16000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........17000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........18000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........19000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........20000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........21000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........22000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........23000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........24000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........25000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........26000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........27000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........28000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........29000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........30000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........31000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........32000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........33000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........34000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........35000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........36000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:........WARNING: Found the following zero-mass residues in protein ent
ry sp|Q9BVL4|SELO_HUMAN : U
MAVYRAALGASLAAARLLPLGRCSPSPAPRSTLSGAAMEPAPRWLAGLRFDNRALRALPVEAPPPGPEGAPSAPRPVPGA
CFTRVQPTPLRQPRLVALSEPALALLGLGAPPAREAEAEAALFFSGNALLPGAEPAAHCYCGHQFGQFAGQLGDGAAMYL
GEVCTATGERWELQLKGAGPTPFSRQADGRKVLRSSIREFLCSEAMFHLGVPTTRAGACVTSESTVVRDVFYDGNPKYEQ
CTVVLRVASTFIRFGSFEIFKSADEHTGRAGPSVGRNDIRVQLLDYVISSFYPEIQAAHASDSVQRNAAFFREVTRRTAR
MVAEWQCVGFCHGVLNTDNMSILGLTIDYGPFGFLDRYDPDHVCNASDNTGRYAYSKQPEVCRWNLRKLAEALQPELPLE
LGEAILAEEFDAEFQRHYLQKMRRKLGLVQVELEEDGALVSKLLETMHLTGADFTNTFYLLSSFPVELESPGLAEFLARL
MEQCASLEELRLAFRPQMDPRQLSMMLMLAQSNPQLFALMGTRAGIARELERVEQQSRLEQLSAAELQSRNQGHWADWLQ
AYRARLDKDLEGAGDAAAWQAEHVRVMHANNPKYVLRNYIAQNAIEAAERGDFSEVRRVLKLLETPYHCEAGAATDAEAT
EADGADGRQRSYSSKPPLWAAELCVTUSS
.37000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........38000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........39000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........40000
.........:.........:.........:.........:.........:.........:.........:.........:
.........  Total: 40896
Computing degenerate peptides for 3057 proteins: 0%...10%...20%...30%...40%...50
%...60%...70%...80%...90%...100%
Computing probabilities for 3208 proteins.  Loop 1: 0%...20%...40%...60%...80%..
.100%  Loop 2: 0%...20%...40%...60%...80%...100%
Computing probabilities for 3208 proteins.  Loop 1: 0%...20%...40%...60%...80%..
.100%  Loop 2: 0%...20%...40%...60%...80%...100%
Computing probabilities for 3208 proteins.  Loop 1: 0%...20%...40%...60%...80%..
.100%  Loop 2: 0%...20%...40%...60%...80%...100%
Computing probabilities for 3208 proteins.  Loop 1: 0%...20%...40%...60%...80%..
.100%  Loop 2: 0%...20%...40%...60%...80%...100%
Computing 2795 protein groups: 0%...10%...20%...30%...40%...50%...60%...70%...80
%...90%...100%
Calculating sensitivity...and error tables...
Computing MU for 3208 proteins: 0%...10%...20%...30%...40%...50%...60%...70%...8
0%...90%...100%
INFO: mu=4.1656e-005, db_size=45481909

Finished
INFO[20:42:08] Done

D:\Users\tangh\Desktop\Philosopher\Test>philosopher filter --pepxml interact-alt
ierid-17-g129-lonp1-normoxia-trypsin4ul-hf.pep.xml --protxml interact.prot.xml
INFO[20:44:08] Executing Filter 20190116
INFO[20:44:08] Processing peptide identification files
INFO[20:44:09] 1+ Charge profile                             decoy=0 target=0
INFO[20:44:09] 2+ Charge profile                             decoy=798 target=67
93
INFO[20:44:09] 3+ Charge profile                             decoy=443 target=41
32
INFO[20:44:09] 4+ Charge profile                             decoy=43 target=644

INFO[20:44:09] 5+ Charge profile                             decoy=7 target=137
INFO[20:44:09] 6+ Charge profile                             decoy=10 target=78
INFO[20:44:09] Database search results                       ions=7850 peptides=
6703 psms=13085
INFO[20:44:09] Converged to 1.00 % FDR with 9549 PSMs        decoy=96 threshold=
0.8366 total=9645
INFO[20:44:09] Converged to 0.99 % FDR with 3911 Peptides    decoy=39 threshold=
0.917 total=3950
INFO[20:44:09] Converged to 1.00 % FDR with 4888 Ions        decoy=49 threshold=
0.9052 total=4937
INFO[20:44:10] Protein inference results                     decoy=1112 target=1
683
INFO[20:44:10] Converged to 1.05 % FDR with 381 Proteins     decoy=4 threshold=0
.9869 total=385
INFO[20:44:10] 2D FDR estimation: Protein mirror image       decoy=381 target=38
1
INFO[20:44:10] Second filtering results                      ions=5479 peptides=
4377 psms=10395
INFO[20:44:10] Converged to 0.61 % FDR with 10332 PSMs       decoy=63 threshold=
0.0518 total=10395
INFO[20:44:10] Converged to 1.00 % FDR with 4286 Peptides    decoy=43 threshold=
0.106 total=4329
INFO[20:44:11] Converged to 0.97 % FDR with 5423 Ions        decoy=53 threshold=
0.0532 total=5476
FATA[20:44:11] Database data not available, interrupting processing

D:\Users\tangh\Desktop\Philosopher\Test>philosopher filter --pepxml interact-alt
ierid-17-g129-lonp1-normoxia-trypsin4ul-hf.pep.xml
INFO[20:45:38] Executing Filter 20190116
INFO[20:45:38] Processing peptide identification files
INFO[20:45:39] 1+ Charge profile                             decoy=0 target=0
INFO[20:45:39] 2+ Charge profile                             decoy=798 target=67
93
INFO[20:45:39] 3+ Charge profile                             decoy=443 target=41
32
INFO[20:45:39] 4+ Charge profile                             decoy=43 target=644

INFO[20:45:39] 5+ Charge profile                             decoy=7 target=137
INFO[20:45:39] 6+ Charge profile                             decoy=10 target=78
INFO[20:45:39] Database search results                       ions=7850 peptides=
6703 psms=13085
INFO[20:45:39] Converged to 1.00 % FDR with 9549 PSMs        decoy=96 threshold=
0.8366 total=9645
INFO[20:45:39] Converged to 0.99 % FDR with 3911 Peptides    decoy=39 threshold=
0.917 total=3950
INFO[20:45:39] Converged to 1.00 % FDR with 4888 Ions        decoy=49 threshold=
0.9052 total=4937
FATA[20:45:40] Database data not available, interrupting processing

D:\Users\tangh\Desktop\Philosopher\Test>

**Comment by prvst** [comment]
@HYTang69 @5utr 
I just released an updated version with a fix to this problem, please try it and let me know.

Thanks for reporting.

**Comment by HYTang69** [comment]
Unfortunately, the updated version did not fix the problem. Still get the same error.

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\tangh>d:

D:\>cd D:\Users\tangh\Desktop\Philosopher\Test2

D:\Users\tangh\Desktop\Philosopher\Test2>philosopher workspace --init
INFO[12:03:48] Executing Workspace 20190204
INFO[12:03:49] Creating workspace
INFO[12:03:49] Done

D:\Users\tangh\Desktop\Philosopher\Test2>philosopher database --id UP000005640 -
-contam --reviewed
INFO[12:04:04] Executing Database 20190204
INFO[12:04:04] Fetching database
INFO[12:04:17] Processing decoys
INFO[12:04:17] Creating file
INFO[12:04:18] Done

D:\Users\tangh\Desktop\Philosopher\Test2>philosopher comet --print
INFO[12:04:49] Executing Comet 20190204
INFO[12:04:50] Printing parameter file
INFO[12:04:50] Done

D:\Users\tangh\Desktop\Philosopher\Test2>philosopher comet --param comet.params
AltieriD-17-G129-LonP1-Normoxia-Trypsin4ul-HF.mzXML
INFO[12:06:55] Executing Comet 20190204
INFO[12:06:55] mz file format not supported for indexing, skipping the indexing

 Comet version "2017.01 rev. 2"

 Search start:  02/05/2019, 12:06:56 PM
 - Input file: D:\Users\tangh\Desktop\Philosopher\Test2\AltieriD-17-G129-LonP1-N
ormoxia-Trypsin4ul-HF.mzXML
   - Load spectra: 36424
     - Search progress: 100%
     - Post analysis:  done
 Search end:    02/05/2019, 12:09:16 PM, 2m:20s

INFO[12:09:16] Done

D:\Users\tangh\Desktop\Philosopher\Test2>philosopher peptideprophet --database 2
019-02-05-td-UP000005640.fas --accmass --decoy rev_ --decoyprobs --nonparam Alti
eriD-17-G129-LonP1-Normoxia-Trypsin4ul-HF.pep.xml
INFO[12:09:41] Executing PeptideProphet 20190204
 file 1: D:\Users\tangh\Desktop\Philosopher\Test2\AltieriD-17-G129-LonP1-Normoxi
a-Trypsin4ul-HF.pep.xml
 processed altogether 36424 results
INFO: Results written to file: D:\Users\tangh\Desktop\Philosopher\Test2\interact
-AltieriD-17-G129-LonP1-Normoxia-Trypsin4ul-HF.pep.xml

  - D:\Users\tangh\Desktop\Philosopher\Test2\interact-AltieriD-17-G129-LonP1-Nor
moxia-Trypsin4ul-HF.pep.xml
  - Building Commentz-Walter keyword tree...
  - Searching the tree...
  - Linking duplicate entries...
  - Printing results...

using Accurate Mass Bins
Using Decoy Label "rev_".
Decoy Probabilities will be reported.
Using non-parametric distributions
 (Comet)
adding ACCMASS mixture distribution
init with Comet stricttrypsin
MS Instrument info: Manufacturer: Thermo Scientific, Model: Q Exactive, Ionizati
on: UNKNOWN, Analyzer: UNKNOWN, Detector: UNKNOWN

INFO: Processing standard MixtureModel ...
 PeptideProphet  (TPP v5.0.1 Post-Typhoon dev, Build 201705191533-7588 (Windows_
NT-x86_64)) AKeller@ISB
 read in 0 1+, 14352 2+, 12821 3+, 4745 4+, 1613 5+, 555 6+, and 0 7+ spectra.
Initialising statistical models ...
Found 11544 Decoys, and 22542 Non-Decoys
Iterations: .........10.........20.......
WARNING: Mixture model quality test failed for charge (1+).
WARNING: Mixture model quality test failed for charge (7+).
model complete after 28 iterations
INFO[12:10:49] Done

D:\Users\tangh\Desktop\Philosopher\Test2>philosopher proteinprophet interact-alt
ierid-17-g129-lonp1-normoxia-trypsin4ul-hf.pep.xml
INFO[12:11:13] Executing ProteinProphet 20190204
ProteinProphet (C++) by Insilicos LLC and LabKey Software, after the original Pe
rl by A. Keller (TPP v5.0.1 Post-Typhoon dev, Build 201705191533-7588 (Windows_N
T-x86_64))
 (no FPKM) (using degen pep info)
Reading in D:/Users/tangh/Desktop/Philosopher/Test2/interact-altierid-17-g129-lo
np1-normoxia-trypsin4ul-hf.pep.xml...
...read in 0 1+, 7590 2+, 4575 3+, 686 4+, 144 5+, 88 6+, 0 7+ spectra with min
prob 0.05

Initializing 7871 peptide weights: 0%...10%...20%...30%...40%...50%...60%...70%.
..80%...90%...100%
Calculating protein lengths and molecular weights from database d:/Users/tangh/D
esktop/Philosopher/Test2/2019-02-05-td-UP000005640.fas
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........1000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........2000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........3000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........4000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........5000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........6000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........7000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........8000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........9000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........10000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........11000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........12000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........13000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........14000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........15000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........16000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........17000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........18000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........19000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........20000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........21000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........22000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........23000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........24000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........25000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........26000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........27000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........28000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........29000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........30000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........31000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........32000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........33000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........34000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........35000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........36000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:........WARNING: Found the following zero-mass residues in protein ent
ry sp|Q9BVL4|SELO_HUMAN : U
MAVYRAALGASLAAARLLPLGRCSPSPAPRSTLSGAAMEPAPRWLAGLRFDNRALRALPVEAPPPGPEGAPSAPRPVPGA
CFTRVQPTPLRQPRLVALSEPALALLGLGAPPAREAEAEAALFFSGNALLPGAEPAAHCYCGHQFGQFAGQLGDGAAMYL
GEVCTATGERWELQLKGAGPTPFSRQADGRKVLRSSIREFLCSEAMFHLGVPTTRAGACVTSESTVVRDVFYDGNPKYEQ
CTVVLRVASTFIRFGSFEIFKSADEHTGRAGPSVGRNDIRVQLLDYVISSFYPEIQAAHASDSVQRNAAFFREVTRRTAR
MVAEWQCVGFCHGVLNTDNMSILGLTIDYGPFGFLDRYDPDHVCNASDNTGRYAYSKQPEVCRWNLRKLAEALQPELPLE
LGEAILAEEFDAEFQRHYLQKMRRKLGLVQVELEEDGALVSKLLETMHLTGADFTNTFYLLSSFPVELESPGLAEFLARL
MEQCASLEELRLAFRPQMDPRQLSMMLMLAQSNPQLFALMGTRAGIARELERVEQQSRLEQLSAAELQSRNQGHWADWLQ
AYRARLDKDLEGAGDAAAWQAEHVRVMHANNPKYVLRNYIAQNAIEAAERGDFSEVRRVLKLLETPYHCEAGAATDAEAT
EADGADGRQRSYSSKPPLWAAELCVTUSS
.37000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........38000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........39000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........40000
.........:.........:.........:.........:.........:.........:.........:.........:
.........  Total: 40896
Computing degenerate peptides for 3057 proteins: 0%...10%...20%...30%...40%...50
%...60%...70%...80%...90%...100%
Computing probabilities for 3208 proteins.  Loop 1: 0%...20%...40%...60%...80%..
.100%  Loop 2: 0%...20%...40%...60%...80%...100%
Computing probabilities for 3208 proteins.  Loop 1: 0%...20%...40%...60%...80%..
.100%  Loop 2: 0%...20%...40%...60%...80%...100%
Computing probabilities for 3208 proteins.  Loop 1: 0%...20%...40%...60%...80%..
.100%  Loop 2: 0%...20%...40%...60%...80%...100%
Computing probabilities for 3208 proteins.  Loop 1: 0%...20%...40%...60%...80%..
.100%  Loop 2: 0%...20%...40%...60%...80%...100%
Computing 2795 protein groups: 0%...10%...20%...30%...40%...50%...60%...70%...80
%...90%...100%
Calculating sensitivity...and error tables...
Computing MU for 3208 proteins: 0%...10%...20%...30%...40%...50%...60%...70%...8
0%...90%...100%
INFO: mu=4.1656e-005, db_size=45481909

Finished
INFO[12:11:18] Done

D:\Users\tangh\Desktop\Philosopher\Test2>philosopher filter --pepxml interact-al
tierid-17-g129-lonp1-normoxia-trypsin4ul-hf.pep.xml --protxml interact.prot.xml
INFO[12:11:49] Executing Filter 20190204
INFO[12:11:49] Processing peptide identification files
INFO[12:11:50] 1+ Charge profile                             decoy=0 target=0
INFO[12:11:50] 2+ Charge profile                             decoy=798 target=67
93
INFO[12:11:50] 3+ Charge profile                             decoy=443 target=41
32
INFO[12:11:50] 4+ Charge profile                             decoy=43 target=644

INFO[12:11:50] 5+ Charge profile                             decoy=7 target=137
INFO[12:11:50] 6+ Charge profile                             decoy=10 target=78
INFO[12:11:50] Database search results                       ions=7850 peptides=
6703 psms=13085
INFO[12:11:50] Converged to 1.00 % FDR with 9549 PSMs        decoy=96 threshold=
0.8366 total=9645
INFO[12:11:50] Converged to 0.99 % FDR with 3911 Peptides    decoy=39 threshold=
0.917 total=3950
INFO[12:11:50] Converged to 1.00 % FDR with 4888 Ions        decoy=49 threshold=
0.9052 total=4937
INFO[12:11:51] Protein inference results                     decoy=1112 target=1
683
INFO[12:11:51] Converged to 1.05 % FDR with 381 Proteins     decoy=4 threshold=0
.9869 total=385
INFO[12:11:51] 2D FDR estimation: Protein mirror image       decoy=381 target=38
1
INFO[12:11:51] Second filtering results                      ions=5479 peptides=
4377 psms=10395
INFO[12:11:51] Converged to 0.61 % FDR with 10332 PSMs       decoy=63 threshold=
0.0518 total=10395
INFO[12:11:51] Converged to 1.00 % FDR with 4286 Peptides    decoy=43 threshold=
0.106 total=4329
INFO[12:11:51] Converged to 0.97 % FDR with 5423 Ions        decoy=53 threshold=
0.0532 total=5476
FATA[12:11:52] Database data not available, interrupting processing

D:\Users\tangh\Desktop\Philosopher\Test2>



________________________________

**Comment by HYTang69** [comment]
Unfortunately the new version still gives the same error:

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\tangh>d:

D:\>cd D:\Users\tangh\Desktop\Philosopher\Test2

D:\Users\tangh\Desktop\Philosopher\Test2>philosopher workspace --init
INFO[12:03:48] Executing Workspace 20190204
INFO[12:03:49] Creating workspace
INFO[12:03:49] Done

D:\Users\tangh\Desktop\Philosopher\Test2>philosopher database --id UP000005640 -
-contam --reviewed
INFO[12:04:04] Executing Database 20190204
INFO[12:04:04] Fetching database
INFO[12:04:17] Processing decoys
INFO[12:04:17] Creating file
INFO[12:04:18] Done

D:\Users\tangh\Desktop\Philosopher\Test2>philosopher comet --print
INFO[12:04:49] Executing Comet 20190204
INFO[12:04:50] Printing parameter file
INFO[12:04:50] Done

D:\Users\tangh\Desktop\Philosopher\Test2>philosopher comet --param comet.params
AltieriD-17-G129-LonP1-Normoxia-Trypsin4ul-HF.mzXML
INFO[12:06:55] Executing Comet 20190204
INFO[12:06:55] mz file format not supported for indexing, skipping the indexing

 Comet version "2017.01 rev. 2"

 Search start:  02/05/2019, 12:06:56 PM
 - Input file: D:\Users\tangh\Desktop\Philosopher\Test2\AltieriD-17-G129-LonP1-N
ormoxia-Trypsin4ul-HF.mzXML
   - Load spectra: 36424
     - Search progress: 100%
     - Post analysis:  done
 Search end:    02/05/2019, 12:09:16 PM, 2m:20s

INFO[12:09:16] Done

D:\Users\tangh\Desktop\Philosopher\Test2>philosopher peptideprophet --database 2
019-02-05-td-UP000005640.fas --accmass --decoy rev_ --decoyprobs --nonparam Alti
eriD-17-G129-LonP1-Normoxia-Trypsin4ul-HF.pep.xml
INFO[12:09:41] Executing PeptideProphet 20190204
 file 1: D:\Users\tangh\Desktop\Philosopher\Test2\AltieriD-17-G129-LonP1-Normoxi
a-Trypsin4ul-HF.pep.xml
 processed altogether 36424 results
INFO: Results written to file: D:\Users\tangh\Desktop\Philosopher\Test2\interact
-AltieriD-17-G129-LonP1-Normoxia-Trypsin4ul-HF.pep.xml

  - D:\Users\tangh\Desktop\Philosopher\Test2\interact-AltieriD-17-G129-LonP1-Nor
moxia-Trypsin4ul-HF.pep.xml
  - Building Commentz-Walter keyword tree...
  - Searching the tree...
  - Linking duplicate entries...
  - Printing results...

using Accurate Mass Bins
Using Decoy Label "rev_".
Decoy Probabilities will be reported.
Using non-parametric distributions
 (Comet)
adding ACCMASS mixture distribution
init with Comet stricttrypsin
MS Instrument info: Manufacturer: Thermo Scientific, Model: Q Exactive, Ionizati
on: UNKNOWN, Analyzer: UNKNOWN, Detector: UNKNOWN

INFO: Processing standard MixtureModel ...
 PeptideProphet  (TPP v5.0.1 Post-Typhoon dev, Build 201705191533-7588 (Windows_
NT-x86_64)) AKeller@ISB
 read in 0 1+, 14352 2+, 12821 3+, 4745 4+, 1613 5+, 555 6+, and 0 7+ spectra.
Initialising statistical models ...
Found 11544 Decoys, and 22542 Non-Decoys
Iterations: .........10.........20.......
WARNING: Mixture model quality test failed for charge (1+).
WARNING: Mixture model quality test failed for charge (7+).
model complete after 28 iterations
INFO[12:10:49] Done

D:\Users\tangh\Desktop\Philosopher\Test2>philosopher proteinprophet interact-alt
ierid-17-g129-lonp1-normoxia-trypsin4ul-hf.pep.xml
INFO[12:11:13] Executing ProteinProphet 20190204
ProteinProphet (C++) by Insilicos LLC and LabKey Software, after the original Pe
rl by A. Keller (TPP v5.0.1 Post-Typhoon dev, Build 201705191533-7588 (Windows_N
T-x86_64))
 (no FPKM) (using degen pep info)
Reading in D:/Users/tangh/Desktop/Philosopher/Test2/interact-altierid-17-g129-lo
np1-normoxia-trypsin4ul-hf.pep.xml...
...read in 0 1+, 7590 2+, 4575 3+, 686 4+, 144 5+, 88 6+, 0 7+ spectra with min
prob 0.05

Initializing 7871 peptide weights: 0%...10%...20%...30%...40%...50%...60%...70%.
..80%...90%...100%
Calculating protein lengths and molecular weights from database d:/Users/tangh/D
esktop/Philosopher/Test2/2019-02-05-td-UP000005640.fas
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........1000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........2000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........3000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........4000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........5000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........6000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........7000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........8000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........9000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........10000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........11000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........12000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........13000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........14000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........15000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........16000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........17000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........18000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........19000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........20000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........21000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........22000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........23000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........24000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........25000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........26000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........27000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........28000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........29000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........30000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........31000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........32000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........33000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........34000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........35000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........36000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:........WARNING: Found the following zero-mass residues in protein ent
ry sp|Q9BVL4|SELO_HUMAN : U
MAVYRAALGASLAAARLLPLGRCSPSPAPRSTLSGAAMEPAPRWLAGLRFDNRALRALPVEAPPPGPEGAPSAPRPVPGA
CFTRVQPTPLRQPRLVALSEPALALLGLGAPPAREAEAEAALFFSGNALLPGAEPAAHCYCGHQFGQFAGQLGDGAAMYL
GEVCTATGERWELQLKGAGPTPFSRQADGRKVLRSSIREFLCSEAMFHLGVPTTRAGACVTSESTVVRDVFYDGNPKYEQ
CTVVLRVASTFIRFGSFEIFKSADEHTGRAGPSVGRNDIRVQLLDYVISSFYPEIQAAHASDSVQRNAAFFREVTRRTAR
MVAEWQCVGFCHGVLNTDNMSILGLTIDYGPFGFLDRYDPDHVCNASDNTGRYAYSKQPEVCRWNLRKLAEALQPELPLE
LGEAILAEEFDAEFQRHYLQKMRRKLGLVQVELEEDGALVSKLLETMHLTGADFTNTFYLLSSFPVELESPGLAEFLARL
MEQCASLEELRLAFRPQMDPRQLSMMLMLAQSNPQLFALMGTRAGIARELERVEQQSRLEQLSAAELQSRNQGHWADWLQ
AYRARLDKDLEGAGDAAAWQAEHVRVMHANNPKYVLRNYIAQNAIEAAERGDFSEVRRVLKLLETPYHCEAGAATDAEAT
EADGADGRQRSYSSKPPLWAAELCVTUSS
.37000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........38000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........39000
.........:.........:.........:.........:.........:.........:.........:.........:
.........:.........40000
.........:.........:.........:.........:.........:.........:.........:.........:
.........  Total: 40896
Computing degenerate peptides for 3057 proteins: 0%...10%...20%...30%...40%...50
%...60%...70%...80%...90%...100%
Computing probabilities for 3208 proteins.  Loop 1: 0%...20%...40%...60%...80%..
.100%  Loop 2: 0%...20%...40%...60%...80%...100%
Computing probabilities for 3208 proteins.  Loop 1: 0%...20%...40%...60%...80%..
.100%  Loop 2: 0%...20%...40%...60%...80%...100%
Computing probabilities for 3208 proteins.  Loop 1: 0%...20%...40%...60%...80%..
.100%  Loop 2: 0%...20%...40%...60%...80%...100%
Computing probabilities for 3208 proteins.  Loop 1: 0%...20%...40%...60%...80%..
.100%  Loop 2: 0%...20%...40%...60%...80%...100%
Computing 2795 protein groups: 0%...10%...20%...30%...40%...50%...60%...70%...80
%...90%...100%
Calculating sensitivity...and error tables...
Computing MU for 3208 proteins: 0%...10%...20%...30%...40%...50%...60%...70%...8
0%...90%...100%
INFO: mu=4.1656e-005, db_size=45481909

Finished
INFO[12:11:18] Done

D:\Users\tangh\Desktop\Philosopher\Test2>philosopher filter --pepxml interact-al
tierid-17-g129-lonp1-normoxia-trypsin4ul-hf.pep.xml --protxml interact.prot.xml
INFO[12:11:49] Executing Filter 20190204
INFO[12:11:49] Processing peptide identification files
INFO[12:11:50] 1+ Charge profile                             decoy=0 target=0
INFO[12:11:50] 2+ Charge profile                             decoy=798 target=67
93
INFO[12:11:50] 3+ Charge profile                             decoy=443 target=41
32
INFO[12:11:50] 4+ Charge profile                             decoy=43 target=644

INFO[12:11:50] 5+ Charge profile                             decoy=7 target=137
INFO[12:11:50] 6+ Charge profile                             decoy=10 target=78
INFO[12:11:50] Database search results                       ions=7850 peptides=
6703 psms=13085
INFO[12:11:50] Converged to 1.00 % FDR with 9549 PSMs        decoy=96 threshold=
0.8366 total=9645
INFO[12:11:50] Converged to 0.99 % FDR with 3911 Peptides    decoy=39 threshold=
0.917 total=3950
INFO[12:11:50] Converged to 1.00 % FDR with 4888 Ions        decoy=49 threshold=
0.9052 total=4937
INFO[12:11:51] Protein inference results                     decoy=1112 target=1
683
INFO[12:11:51] Converged to 1.05 % FDR with 381 Proteins     decoy=4 threshold=0
.9869 total=385
INFO[12:11:51] 2D FDR estimation: Protein mirror image       decoy=381 target=38
1
INFO[12:11:51] Second filtering results                      ions=5479 peptides=
4377 psms=10395
INFO[12:11:51] Converged to 0.61 % FDR with 10332 PSMs       decoy=63 threshold=
0.0518 total=10395
INFO[12:11:51] Converged to 1.00 % FDR with 4286 Peptides    decoy=43 threshold=
0.106 total=4329
INFO[12:11:51] Converged to 0.97 % FDR with 5423 Ions        decoy=53 threshold=
0.0532 total=5476
FATA[12:11:52] Database data not available, interrupting processing

D:\Users\tangh\Desktop\Philosopher\Test2>

**Comment by prvst** [comment]
@HYTang69 I got the wrong binaries uploaded by mistake, I replaced them last night, they have the same name and version. Could you download Philosopher and try again ?

**Comment by prvst** [comment]
I believe to have fixed the issue with the release from today, please give it a try and let me know.
Thanks for reporting the issue.

**Comment by 5utr** [comment]
Still getting the same error with today's release:

`-bash-4.1$ ./philosopher_linux_amd64 filter --pepxml interact-TMT1_1.pep.xml
INFO[10:55:42] Executing Filter 20190206
INFO[10:55:42] Processing peptide identification files
INFO[10:55:45] 1+ Charge profile                             decoy=0 target=0
INFO[10:55:45] 2+ Charge profile                             decoy=540 target=7375
INFO[10:55:45] 3+ Charge profile                             decoy=711 target=8356
INFO[10:55:45] 4+ Charge profile                             decoy=177 target=2261
INFO[10:55:45] 5+ Charge profile                             decoy=0 target=0
INFO[10:55:45] 6+ Charge profile                             decoy=0 target=0
INFO[10:55:45] Database search results                       ions=8208 peptides=6996 psms=19420
INFO[10:55:45] Converged to 1.00 % FDR with 16116 PSMs       decoy=162 threshold=0.7821 total=16278
INFO[10:55:45] Converged to 0.99 % FDR with 4944 Peptides    decoy=49 threshold=0.9156 total=4993
INFO[10:55:45] Converged to 0.99 % FDR with 6038 Ions        decoy=60 threshold=0.8988 total=6098
FATA[10:55:45] Database data not available, interrupting processing
`

**Comment by prvst** [comment]
did you removed the folder and started from the beginning?

**Comment by 5utr** [comment]
Yes started from scratch with the new release.

**Comment by HYTang69** [comment]
Ok. Today's version works for me. No more "Database data not available, interrupting processing" error. Thanks. Would like to continue with the tutorial but the link (https://github.com/Nesvilab/philosopher/blob/master/tutorial.md) is broken.

**Comment by 5utr** [comment]
It works for me too. In the last try I didn't regenerate the database after --init. Does it mean the same reference proteome cannot be use for multiple analysis but it has to be generate every time?

**Comment by prvst** [comment]
No, the reference proteome can be used for multiple analysis. The reason I asked you to run those commands again is because the bug you found was in that function. Normally, the database creation / annotation needs to be executed only once.
