### ISSUE TITLE
philosophers on Linux analysis for AP-MS data

### ISSUE THREAD

**Issue by prvst** [Nesvilab/philosopher#295]
### Discussed in https://github.com/Nesvilab/philosopher/discussions/277

<div type='discussions-op-text'>

<sup>Originally posted by **Bin-cc** September 27, 2021</sup>
Hi,

Thank you for doing such an outstanding work. There are some questions I would like to ask you. I've run into some problems running philosopher on a compute cluster (CentOS 7 Linux). The `philosopher.yml` and `comet.params` are referenced from [this](https://github.com/Nesvilab/philosopher/wiki/REPRINT-Analysis). And the log is as follows.

```
time="14:58:00" level=info msg="Executing Pipeline  v4.0.0"
time="14:58:00" level=info msg="Creating workspace"
time="14:58:00" level=warning msg="A meta data folder was found and will not be overwritten. "
time="14:58:00" level=info msg="Initiating the workspace on /bin/A1BG/A1BG_1"
time="14:58:00" level=info msg="Creating workspace"
time="14:58:00" level=warning msg="A meta data folder was found and will not be overwritten. "
time="14:58:00" level=info msg="Initiating the workspace on /bin/A1BG/A1BG_2"
time="14:58:00" level=info msg="Creating workspace"
time="14:58:00" level=warning msg="A meta data folder was found and will not be overwritten. "
time="14:58:00" level=info msg="Annotating the database"
time="14:58:12" level=info msg="Running the Database Search"
time="14:58:12" level=fatal msg="Missing parameter file or data file for analysis. "
```
The reason seems to be that the system cannot find my `comet.params` or `.mzml` file. I'm sure my file path is fine. The same operation I have successfully implemented on Windows, but for some reason I am having problems on Linux. I was a little confused as to why this was the case. Thank you!

Best ragards,

Bin
</div>

**Comment by sarah-haynes** [comment]
Hi Bin, can you double check that in the `comet:` section, the input format is written as `raw: mzML` instead of `extension: mzML`, and that `search_engine` is set to `comet`?

**Comment by sarah-haynes** [comment]
Hi Bin, regarding the latest issue:

> The problem of .meta/razor.bin is indeed solved. Thank you. But instead, I enconuter a new problem as follows.
INFO[13:56:23] Protein inference results                     decoy=20 target=4202
INFO[13:56:23] Converged to 0.08 % FDR with 1238 Proteins    decoy=1 threshold=0.9975 total=1239
2021/11/20 13:56:24 RemoveAll .: invalid argument
I can get combined.pep.xml and combined.prot.xml, but .tsv are not generated. I'm sure it's with the latest .yml and comet.params, and set the parameters as you said. What else should I do?

 Can you confirm that you're running this set of commands on multiple sub-folders, each containing different spectral files?

--Sarah

**Comment by prvst** [comment]
@Bin-cc. I was not able to reproduce your error. I ran version 4.1.1, with your data, database, and the parameter file. I cleaned the work directories, removed the temporary files, and changed the protein inference to no. The pipeline executed nicely all the way to the end without errors. See the data files attached. I ask you to try again with a clean folder, and fresh files, one more time. At this point because we cannot reproduce this issue, and because we got the results, I'll close your issue. Please fel free to open i again if you have further issues.

[277.zip](https://github.com/Nesvilab/philosopher/files/7808975/277.zip)

**Comment by prvst** [comment]
@Bin-cc can you share your whole data with us?

**Comment by prvst** [comment]
Scratch that, we implemented a fix for your issue, a new version will be out soon. Thanks for reporting,

**Comment by Bin-cc** [comment]
Dear Philosopher group,

I had tried again in a new and clean workspace and changed Protein
Inference to no. However, I still encounter the same problem.

INFO[11:02:45] Protein inference results                     decoy=20
target=4206
INFO[11:02:45] Converged to 1.03 % FDR with 1549 Proteins    decoy=16
threshold=0.9197 total=1565
2022/01/05 11:02:46 RemoveAll .: invalid argument

I changed my data and database, but before using the latest version, I had
tested it with v3. 4. 13 and ran it successfully. I'm also wondering why I
can't run it successfully with the latest version, so I attach my data and
database to you, could you use it to test again? The parameters from
philosopher.yml and comet.param are default.

Thank you for helping me find the root of the problem.

Best regards,
Bin
 test.zip
<https://drive.google.com/file/d/1bB_Y7-QJaICU2C5uF9wuqyDwvN0-DL25/view?usp=drive_web>


Felipe da Veiga Leprevost ***@***.***> 于2022年1月5日周三 00:32写道：

**Comment by prvst** [comment]
@Bin-cc We added a fix to your issue into the latest version, soon to be released. Thanks for reporting.

Fixed. Added to v4.2.1.

**Comment by fcgportal** [comment]
> 

Hi there, I am facing the same problems. Is there any way to solve it? Thanks so much.

**Comment by Bin-cc** [comment]
Hi, I'm still waiting for the latest version and have no idea about it.

> > 
> 
> Hi there, I am facing the same problems. Is there any way to solve it? Thanks so much.

**Comment by prvst** [comment]
We added some extensive changes to the program the require more testing, but we should have something soon, thanks for being poatient.
