### ISSUE TITLE
wrong assignment of decoy hits

### ISSUE THREAD

**Issue by FantacticMisterFox** [Nesvilab/philosopher#51]
Sorry do bother again got the same issue like the last issue.
The report or the filter does not correctly assign decoy hits. Even with the newest version, where you implemented the feature that all other programs down stream do get the information of the decoy tag from the database program.
My calls are the following:

```
philosopher_linux_386 workspace --init
philosopher_linux_386 database --custom $current_db --prefix rev_
philosopher_linux_386 comet --param ./current_comet.params "./$mz/$mz.mzML"
philosopher_linux_386 peptideprophet --database "$current_db" --decoy rev_ --accmass --decoyprobs --nonparam "./$mz/${mz}_decoy.pep.xml"
philosopher_linux_386 proteinprophet "./$mz/interact-${mz}_decoy.pep.xml"
cp ./interact.prot.xml "./$mz/interact-${mz}_decoy.prot.xml"
philosopher_linux_386 filter --pepxml "./$mz/interact-${mz}_decoy.pep.xml" --protxml "./$mz/interact-${mz}_decoy.prot.xml" --tag rev_
philosopher_linux_386 report --decoys
```

I can also make the call like so (removing every argument for deoy tag, should also work now with the new feature):

```
philosopher_linux_386 workspace --init
philosopher_linux_386 database --custom $current_db
philosopher_linux_386 comet --param ./current_comet.params "./$mz/$mz.mzML"
philosopher_linux_386 peptideprophet --database "$current_db" --accmass --decoyprobs --nonparam "./$mz/${mz}_decoy.pep.xml"
philosopher_linux_386 proteinprophet "./$mz/interact-${mz}_decoy.pep.xml"
cp ./interact.prot.xml "./$mz/interact-${mz}_decoy.prot.xml"
philosopher_linux_386 filter --pepxml "./$mz/interact-${mz}_decoy.pep.xml" --protxml "./$mz/interact-${mz}_decoy.prot.xml"
philosopher_linux_386 report --decoys
```

**Comment by prvst** [comment]
@FantacticMisterFox 

We recently found an issue with the decoy reporting and we are currently working on it, that's probably affecting your results too. I'll have a fix soon.
Also, you are not bothering, you are actually providing feedback so we can improve our tools, and we are pleased for that.

**Comment by prvst** [comment]
@FantacticMisterFox 

I released an updated today, can you try that one ?

**Comment by FantacticMisterFox** [comment]
nope still wrong assignments. with or without the argument. Further a new file is created "delta-mass.html"

**Comment by prvst** [comment]
Can you share your tsv tables with me?

**Comment by FantacticMisterFox** [comment]
sure.
http://www.bioinf.uni-leipzig.de/~john/data.tgz

**Comment by prvst** [comment]
@FantacticMisterFox 

The problem is with your database file, you are not using a standard format so Philosopher doesn't know how to process it. You can download a database file using Philosopher or directly from UniProt, just make sure you are following their [specification](https://www.uniprot.org/help/fasta-headers). Philosopher is also compatible with formats from NCBI and ENSEMBL.
